import { loadEnv } from "@/config";
import { ENVT } from "@/types";

loadEnv();

export const RESPONSE_CODES = {
  SUCCESS: "SUCCESS",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED",
  NO_CONTENT: "NO_CONTENT",
  CONFLICT: "CONFLICT",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  TO_MANY_REQUESTS: "TO_MANY_REQUEST",
};

export const ENV: ENVT = {
  // Facebook
  FACEBOOK_APP_ID: process.env.FB_APP_ID!,
  FACEBOOK_APP_SECRET: process.env.FB_SECRET!,
  FACEBOOK_REDIRECT_URI: process.env.FB_REDIRECT_URI!,
  FACEBOOK_SCOPE: process.env.FB_SCOPE!,
  FACEBOOK_RESPONSE_TYPE: process.env.FB_RESPONSE_TYPE!,
  FACEBOOK_OAUTH_URL: process.env.FB_OAUTH_URL!,
  FACEBOOK_VERIFY_URL: process.env.FB_VERIFY_URL!,
  FACEBOOK_RESPONSE_URL: process.env.FB_RESPONSE_URL!,
  FACEBOOK_FIELDS: process.env.FB_FIELDS!,
  // Google
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_SECRET_ID: process.env.GOOGLE_SECRET_ID!,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI!,
  // JWT
  ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY!,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY!,
  JWT_SECRET: process.env.JWT_SECRET!,
};
