import { constantTemFNamesT, ENVT } from "@/types";

export const RESPONSE_CODES = {
  SUCCESS: "SUCCESS",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED",
  NO_CONTENT: "NO_CONTENT",
  CONFLICT: "CONFLICT",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  TO_MANY_REQUESTS: "TO_MANY_REQUEST"
};


export const TEMPLATE_FOLDER_NAME: constantTemFNamesT = {
  AUTH: "auth",
};



export const ENV: ENVT = {
  AMQP_HOST: process.env.AMQP_HOST!,
};
